# Generated by Django 4.2.14 on 2024-09-21 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('author', models.CharField(max_length=128, verbose_name='著者')),
                ('pages', models.IntegerField(blank=True, verbose_name='ページ数')),
                ('price', models.IntegerField(blank=True, verbose_name='価格')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32, verbose_name='状態')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='読了日')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開する')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reading_log.book', verbose_name='書籍')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reading_log.bookstatus', verbose_name='状態')),
            ],
        ),
        migrations.AddConstraint(
            model_name='readinglog',
            constraint=models.UniqueConstraint(fields=('book', 'created_by'), name='book_created_by_unique'),
        ),
    ]
